name: ci-cd
on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main, develop]

permissions:
  contents: read
  id-token: write

jobs:
  pipeline:
    uses: UNIANDES-202515-PROYECTO-II-G17-BACKEND/.github/workflows/frontend-service.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      node_version: '20'
    secrets: inherit
